[window]
opacity = 0.85
startup_mode = "Maximized"
decorations = "None"
blur = true

[font]
size = 12.0
normal.family = "Mononoki Nerd Font"
bold.family = "Mononoki Nerd Font"
italic.family = "Mononoki Nerd Font"
bold_italic.family = "Mononoki Nerd Font"

[bell]
duration = 1
animation = "Ease"

[general]
# this import will be auto changed
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
